Windows: zfs_enter rework
openzfsonwindows/openzfs pull request #151
Opened 2022-09-27 11:22 UTC by andrewc12

This needs going over.
I don't know if I've replace the right variables from ZFS_VERIFY_ZP_ERROR, and there may be and extra unnecessary error added.
Also do we need to convert errors to some windows specific format?

### Motivation and Context

### Description

### How Has This Been Tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-09-27 12:22 UTC, yurikoles requested changes

2022-09-27 12:22 UTC, yurikoles commented on module/os/windows/zfs/zfs_vfsops.c
> +	int error = 0;
Please align with code above.

2022-09-27 12:35 UTC, andrewc12 commented on module/os/windows/zfs/zfs_vfsops.c
> +	int error = 0;
> Please align with code above.

Will do

2022-10-01 05:17 UTC, lundman approved these changes

2022-10-01 05:17 UTC, lundman commented on include/os/linux/zfs/sys/zfs_znode_impl.h
> +static inline int
Linux has ZPL_ENTER because the linux kernel expects negative error codes, so macOS (freebsd) can just use ZFS_ENTER instead.

2022-10-01 05:17 UTC, lundman commented on module/os/windows/zfs/zfs_vfsops.c
> +		return (error);
indentation?

2022-10-01 06:40 UTC, merged